[package]
name = "onboarder"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket ={ version = "0.5.0" } 
maud = { version = "0.25" }
chrono ="0.4.38"
uuid = { version ="1.11.0", features = ["v4", "fast-rng", "macro-diagnostics"] }


[profile.dev]
opt-level = 0
