on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  plan:
     runs-on: "ubuntu-20.04"
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Rust setup
       uses: dtolnay/rust-toolchain@stable
     - name: Rust cache
       uses: swatinem/rust-cache@v2
  
     - uses: taiki-e/install-action@v2
       with:
        tool: just@1
 
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ github.repository_owner }}
         password: ${{ github.token }}
 
     - name: Build and push Docker image
       run: |
         just build
         just build-docker
         just push $CARGO_PKG_VERSION